### PR TITLE
Improve the category selection

### PR DESCRIPTION
**Pull request by MrMusic**
Entering the category IDs manually is not user-friendly.

This PR offers the possibility to select the categories by name or ID.

### CODE REVIEW

**Comment by Erftralle** [comment]
Thank you for your suggestion, which I generally like very much 👍 .

What I don't like in detail is that there is a "Category selection mode" for the "Category filter". This is not only redundant and unnecessary, but also only leads to confusion and errors when changing the mode, since the filter is not transferred automatically.

I would just use the modern mode with the "old" parameter "blacklist_cats" and convert the existing CSV list during the update process. Maybe you could do this with the help of a "script.php".

**Comment by MrMusic** [comment]
>What I don't like in detail is that there is a "Category selection mode" for the "Category filter"...

I was afraid that you would say that ;-)
That's how i wanted it at the beginning.
Unfortunately, the params from the old format are not automatically converted to the "new" format.
So i then offered both options to choose from.

Now i have inserted a conversion during the update.
Maybe you can solve it more elegantly, but i don't know how...

**Comment by Erftralle** [comment]
>  Now i have inserted a conversion during the update.

Yes, that's how I would have solved it too. 👍 
 
I have created MrMusic/JoomCategories#1 with some suggestions of small improvements:

- The code to convert the configuration parameter is only executed in case of an update
- It is considered that there might be used more than one instance of the module on the site
- The code to convert the parameter itself is more robust against the insertion or deletion of configuration parameters in future releases

**Comment by Erftralle** [comment]
Thank you for merging my suggestions.

Would you mind to adjust the Dutch language files as well. I think this shouldn't be that difficult since only the term "ID" is dropped.

**Comment by MrMusic** [comment]
Thank you for your suggestions @Erftralle 
The Dutch langauge file is now updated.

**Comment by Erftralle** [comment]
Thank you very much.

I have just one question:
Can you please explain the last commit https://github.com/JoomGalleryfriends/JoomCategories/pull/4/commits/bc9c89e6eee33cbb8b92b7aa41a90bfff0f3a1ff to me. GitHub says  **_"Merge branch 'Improve-category-seelction' of https://github.com/MrMusic/JoomCategories into Improve-category-seelction"_**.  That sounds to me as if source and destination are equal? How did this commit come about? Please do not get me wrong. I don't see any errors, I just want to understand the commit.

**Comment by MrMusic** [comment]
>I have just one question:...

I can only guess where the commit bc9c89e comes from.
First I merged your pull request https://github.com/MrMusic/JoomCategories/pull/1 here directly on Github.
Then I updated the clone that is locally on my PC in order to then change the Dutch language file and commit with 391022c.
The commit bc9c89e was probably caused by updating my local repo.

**Comment by Erftralle** [comment]
Thanks for the explanation.

I have tested this item ✅ successfully.

**Pull request merged**
